//
// Created by Electrux Redsworth on 9/12/17.
//

#ifndef HASHTABLEIMPLEMENTATION_CONSTS_HPP
#define HASHTABLEIMPLEMENTATION_CONSTS_HPP

const int MAX_TABLES = 100000;
const int TABLE_SIZE = 138;

#endif //HASHTABLEIMPLEMENTATION_CONSTS_HPP
